# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.IntegerField()),
                ('site_number', models.IntegerField()),
                ('site_loop', models.CharField(max_length=2)),
                ('phone_number', models.IntegerField()),
                ('occupants', models.IntegerField()),
                ('vehicles', models.IntegerField()),
                ('site_type', models.CharField(max_length=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('season_open', models.DateField()),
                ('season_closed', models.DateField()),
                ('status', models.CharField(max_length=45)),
                ('water', models.CharField(max_length=255)),
                ('number_sites', models.IntegerField()),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorites', models.ManyToManyField(related_name='favorited_campsites', to='project_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campsite',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsites', to='project_app.Park'),
        ),
        migrations.AddField(
            model_name='booking',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_bookings', to='project_app.Campsite'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ManyToManyField(related_name='bookings', to='project_app.User'),
        ),
    ]
